package view.component.contentpane;

import contoller.TrialBeginViewController;
import sitting.SittingManager;
import sitting.SittingState;

/**
 *
 * @author Philippe
 */
public class TrialBeginContentPane extends AbstractContentPane {
    
    private TrialBeginViewController m_controller;
    /**
     * Creates new form TrialBeginContentPane
     */
    public TrialBeginContentPane(SittingManager sittingManager) {
        super(sittingManager);
        initComponents();
        m_controller = new TrialBeginViewController(sittingManager);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        begin_button = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        begin_button.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        begin_button.setText("Toucher pour débuter");
        begin_button.setEnabled(false);
        begin_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                begin_buttonActionPerformed(evt);
            }
        });
        add(begin_button, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void begin_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_begin_buttonActionPerformed
        m_controller.startFirstTrial();
    }//GEN-LAST:event_begin_buttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton begin_button;
    // End of variables declaration//GEN-END:variables

    @Override
    public void handleStateChange() {
        if(this.getSittingManager().getState().equals(SittingState.START_OF_BLOCK)){
               begin_button.setEnabled(true);
        }
    }
}
